from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.api.schemas import (
    EligibilityRequest,
    EligibilityResponse,
)
from app.db.base import get_db
from app.pipeline.recommendation import RecommendationPipeline

router = APIRouter()


@router.post(
    "/eligibility",
    response_model=EligibilityResponse,
)
async def get_eligible_schemes(
    request: EligibilityRequest, db: Session = Depends(get_db)
):
    """
    Identifies government schemes for which a given profile is eligible.
    """
    pipeline = RecommendationPipeline()
    # Convert string profile_id to UUID before passing to pipeline
    try:
        profile_uuid = UUID(request.profile_id)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid profile ID format: {request.profile_id}",
        )

    # The run method returns a full report, we need to extract eligible schemes from it
    report = await pipeline.run(profile_uuid, db)

    if "error" in report:
        if report["error"] == "Profile not found":
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND, detail=report["error"]
            )
        else:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=report["error"],
            )

    # Extract eligible schemes from the report generated by the pipeline
    eligible_schemes_results = report.get("eligibility_results", [])
    profile_id_str = str(request.profile_id)

    return EligibilityResponse(
        profile_id=profile_id_str,
        eligible_schemes=eligible_schemes_results,
        total_matches=len(eligible_schemes_results),
        search_query=f"Profile ID: {request.profile_id}",  # Placeholder for actual search query
    )
